import {
  type BusinessConfig,
  TaxRegime,
  ProductCategory,
  type Product,
} from '../types';

export const defaultBusinessConfig: BusinessConfig = {
  storeName: 'Minha Adega',
  taxConfig: {
    regime: TaxRegime.SIMPLES_NACIONAL,
    aliquotaEfetiva: 0.06,
    rbt12: 360000,
  },
  fixedCosts: [
    { id: '1', name: 'Aluguel', monthlyCost: 3500 },
    { id: '2', name: 'Energia Eletrica', monthlyCost: 800 },
    { id: '3', name: 'Agua', monthlyCost: 150 },
    { id: '4', name: 'Internet/Telefone', monthlyCost: 200 },
    { id: '5', name: 'Folha de Pagamento', monthlyCost: 5000 },
    { id: '6', name: 'Contador', monthlyCost: 600 },
    { id: '7', name: 'Sistema/Software', monthlyCost: 150 },
    { id: '8', name: 'Outros', monthlyCost: 300 },
  ],
  variableCosts: [
    { id: '1', name: 'Embalagens', rate: 0.50, isPercentage: false },
    { id: '2', name: 'Perdas/Quebras', rate: 1.0, isPercentage: true },
  ],
  paymentFees: [
    { id: '1', name: 'Credito a Vista', fee: 2.99, salesShare: 30 },
    { id: '2', name: 'Credito Parcelado 2-6x', fee: 4.49, salesShare: 15 },
    { id: '3', name: 'Credito Parcelado 7-12x', fee: 5.99, salesShare: 5 },
    { id: '4', name: 'Debito', fee: 1.59, salesShare: 25 },
    { id: '5', name: 'PIX', fee: 0.00, salesShare: 20 },
    { id: '6', name: 'Dinheiro', fee: 0.00, salesShare: 5 },
  ],
  estimatedMonthlySales: 80000,
  estimatedMonthlyUnitsSold: 2000,
  marginTargets: [
    { category: ProductCategory.VINHOS, targetMarginPercent: 30 },
    { category: ProductCategory.CERVEJAS, targetMarginPercent: 25 },
    { category: ProductCategory.DESTILADOS, targetMarginPercent: 35 },
    { category: ProductCategory.SALGADINHOS, targetMarginPercent: 40 },
    { category: ProductCategory.CARNES, targetMarginPercent: 20 },
    { category: ProductCategory.OUTROS, targetMarginPercent: 30 },
  ],
};

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Vinho Casillero del Diablo',
    category: ProductCategory.VINHOS,
    supplier: 'Distribuidora Bacchus',
    costPrice: 32.0,
    sellingPrice: 59.90,
    isAutoPrice: false,
    unit: 'un',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Cerveja Heineken 600ml',
    category: ProductCategory.CERVEJAS,
    supplier: 'Ambev',
    costPrice: 5.80,
    sellingPrice: 12.90,
    isAutoPrice: false,
    unit: 'un',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Whisky Jack Daniels 1L',
    category: ProductCategory.DESTILADOS,
    supplier: 'Distribuidora Premium',
    costPrice: 89.0,
    sellingPrice: 169.90,
    isAutoPrice: false,
    unit: 'un',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Amendoim Japones 500g',
    category: ProductCategory.SALGADINHOS,
    supplier: 'Distribuidora Snacks',
    costPrice: 4.50,
    sellingPrice: 12.90,
    isAutoPrice: false,
    unit: 'un',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Picanha Bovina 1kg',
    category: ProductCategory.CARNES,
    supplier: 'Frigorifico Boi Gordo',
    costPrice: 55.0,
    sellingPrice: 79.90,
    isAutoPrice: false,
    unit: 'kg',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Cerveja Brahma Duplo Malte 350ml',
    category: ProductCategory.CERVEJAS,
    supplier: 'Ambev',
    costPrice: 2.10,
    sellingPrice: 4.99,
    isAutoPrice: false,
    unit: 'un',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Vodka Absolut 1L',
    category: ProductCategory.DESTILADOS,
    supplier: 'Distribuidora Premium',
    costPrice: 42.0,
    sellingPrice: 84.90,
    isAutoPrice: false,
    unit: 'un',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Carvao Vegetal 4kg',
    category: ProductCategory.OUTROS,
    supplier: 'Fornecedor Local',
    costPrice: 12.0,
    sellingPrice: 24.90,
    isAutoPrice: false,
    unit: 'un',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
