-- ============================================
-- ADEGA PRICING - Setup Supabase COMPLETO
-- Execute este SQL no SQL Editor do Supabase
-- ============================================

-- Limpar tabelas se existirem
DROP TABLE IF EXISTS simulation_scenarios CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS business_config CASCADE;
DROP FUNCTION IF EXISTS update_updated_at CASCADE;

-- Tabela de configuracao do negocio
CREATE TABLE business_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_name text NOT NULL DEFAULT 'Minha Adega',
  tax_regime text NOT NULL DEFAULT 'SIMPLES_NACIONAL',
  tax_config jsonb NOT NULL DEFAULT '{}',
  fixed_costs jsonb NOT NULL DEFAULT '[]',
  variable_costs jsonb NOT NULL DEFAULT '[]',
  payment_fees jsonb NOT NULL DEFAULT '[]',
  estimated_monthly_sales numeric NOT NULL DEFAULT 80000,
  estimated_monthly_units_sold numeric NOT NULL DEFAULT 2000,
  margin_targets jsonb NOT NULL DEFAULT '[]',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text NOT NULL,
  supplier text NOT NULL DEFAULT '',
  cost_price numeric NOT NULL DEFAULT 0,
  selling_price numeric NOT NULL DEFAULT 0,
  is_auto_price boolean NOT NULL DEFAULT true,
  unit text NOT NULL DEFAULT 'un',
  notes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE simulation_scenarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  adjustments jsonb NOT NULL DEFAULT '[]',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS
ALTER TABLE business_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE simulation_scenarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all on business_config" ON business_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on products" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on simulation_scenarios" ON simulation_scenarios FOR ALL USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_business_config_updated_at
  BEFORE UPDATE ON business_config
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- SEED: Configuracao do negocio
INSERT INTO business_config (
  store_name, tax_regime, tax_config, fixed_costs, variable_costs,
  payment_fees, estimated_monthly_sales, estimated_monthly_units_sold, margin_targets
) VALUES (
  'Fonte Certa Adega',
  'SIMPLES_NACIONAL',
  '{"regime": "SIMPLES_NACIONAL", "aliquotaEfetiva": 0.06, "rbt12": 360000}',
  '[
    {"id": "1", "name": "Aluguel", "monthlyCost": 3500},
    {"id": "2", "name": "Energia Eletrica", "monthlyCost": 800},
    {"id": "3", "name": "Agua", "monthlyCost": 150},
    {"id": "4", "name": "Internet/Telefone", "monthlyCost": 200},
    {"id": "5", "name": "Folha de Pagamento", "monthlyCost": 5000},
    {"id": "6", "name": "Contador", "monthlyCost": 600},
    {"id": "7", "name": "Sistema/Software", "monthlyCost": 150},
    {"id": "8", "name": "Outros", "monthlyCost": 300}
  ]',
  '[
    {"id": "1", "name": "Embalagens", "rate": 0.50, "isPercentage": false},
    {"id": "2", "name": "Perdas/Quebras", "rate": 1.0, "isPercentage": true}
  ]',
  '[
    {"id": "1", "name": "Credito a Vista", "fee": 2.99, "salesShare": 30},
    {"id": "2", "name": "Credito Parcelado 2-6x", "fee": 4.49, "salesShare": 15},
    {"id": "3", "name": "Credito Parcelado 7-12x", "fee": 5.99, "salesShare": 5},
    {"id": "4", "name": "Debito", "fee": 1.59, "salesShare": 25},
    {"id": "5", "name": "PIX", "fee": 0.00, "salesShare": 20},
    {"id": "6", "name": "Dinheiro", "fee": 0.00, "salesShare": 5}
  ]',
  80000,
  2000,
  '[{"category": "Vinhos", "targetMarginPercent": 30}, {"category": "Cervejas", "targetMarginPercent": 25}, {"category": "Destilados", "targetMarginPercent": 35}, {"category": "Cachacas", "targetMarginPercent": 35}, {"category": "Drinks", "targetMarginPercent": 50}, {"category": "Doses", "targetMarginPercent": 60}, {"category": "Kits", "targetMarginPercent": 30}, {"category": "Energeticos", "targetMarginPercent": 40}, {"category": "Bebidas Nao Alcoolicas", "targetMarginPercent": 40}, {"category": "Salgadinhos", "targetMarginPercent": 45}, {"category": "Churrasco", "targetMarginPercent": 30}, {"category": "Tabacaria", "targetMarginPercent": 40}, {"category": "Acessorios", "targetMarginPercent": 50}, {"category": "Promocoes", "targetMarginPercent": 15}, {"category": "Outros", "targetMarginPercent": 30}]'
);

-- ============================================
-- SEED: Todos os 311 produtos ativos
-- ============================================
INSERT INTO products (name, category, supplier, cost_price, selling_price, is_auto_price, unit, notes) VALUES
  ('Whisky Jack James 900ml Dark Berry', 'Destilados', 'Whisky Jack James', 0, 20.0, false, 'un', 'Estoque: 8'),
  ('Doses Whisky Jack James', 'Destilados', 'Whisky Jack James', 0, 10.0, false, 'un', 'Estoque: 0'),
  ('Whisky Jack James 900ml  Maça Verde', 'Destilados', 'Whisky Jack James', 0, 20.0, false, 'un', 'Estoque: 8'),
  ('Whisky Jack James 900ml Mel e Limão', 'Destilados', 'Whisky Jack James', 0, 20.0, false, 'un', 'Estoque: 5'),
  ('Cachaça cabaré prata', 'Cachacas', 'Cachaça', 0, 30.0, false, 'un', 'Estoque: 3'),
  ('Saque Sakai', 'Cachacas', 'Cachaça', 0, 26.0, false, 'un', 'Estoque: 9'),
  ('Duelo Morango', 'Cachacas', 'Cachaça', 0, 5.0, false, 'un', 'Estoque: 6'),
  ('Cachaça Cabaré', 'Cachacas', 'Cachaça', 0, 320.0, false, 'un', 'Estoque: 1'),
  ('Canelinha da Rocha 275ml', 'Cachacas', 'Cachaça', 0, 5.0, false, 'un', 'Estoque: 18'),
  ('Pitu 965ml', 'Cachacas', 'Cachaça', 0, 14.0, false, 'un', 'Estoque: 10'),
  ('DomecQ 1L', 'Cachacas', 'Cachaça', 0, 55.0, false, 'un', 'Estoque: 12'),
  ('Duelo Blue', 'Cachacas', 'Cachaça', 0, 5.0, false, 'un', 'Estoque: 6'),
  ('51  965ml', 'Cachacas', 'Cachaça', 0, 14.0, false, 'un', 'Estoque: 2'),
  ('Seleta prata', 'Cachacas', 'Cachaça', 0, 35.0, false, 'un', 'Estoque: 5'),
  ('Pitu 710ml', 'Cachacas', 'Cachaça', 0, 13.0, false, 'un', 'Estoque: 33'),
  ('Kariri 960ml', 'Cachacas', 'Cachaça', 0, 19.0, false, 'un', 'Estoque: 8'),
  ('Dreher 900ml', 'Cachacas', 'Cachaça', 0, 26.0, false, 'un', 'Estoque: 12'),
  ('Campari 998ml', 'Cachacas', 'Cachaça', 0, 58.0, false, 'un', 'Estoque: 11'),
  ('Ypioca', 'Cachacas', 'Cachaça', 0, 25.0, false, 'un', 'Estoque: 1'),
  ('Groselha Cachoeira 920ml', 'Cachacas', 'Cachaça', 0, 15.0, false, 'un', 'Estoque: 1'),
  ('Duelo Pessego', 'Cachacas', 'Cachaça', 0, 5.0, false, 'un', 'Estoque: 5'),
  ('Canelinha da Rocha 900ml', 'Cachacas', 'Cachaça', 0, 15.0, false, 'un', 'Estoque: 17'),
  ('Paratudo 900ml', 'Cachacas', 'Cachaça', 0, 16.0, false, 'un', 'Estoque: 8'),
  ('Tequila José Cuervo', 'Cachacas', 'Cachaça', 0, 115.0, false, 'un', 'Estoque: 4'),
  ('José Cuervo Prata', 'Cachacas', 'Cachaça', 0, 115.0, false, 'un', 'Estoque: 5'),
  ('Pitu Limão 350ml', 'Cachacas', 'Cachaça', 0, 6.0, false, 'un', 'Estoque: 50'),
  ('Malibu', 'Cachacas', 'Cachaça', 0, 58.0, false, 'un', 'Estoque: 6'),
  ('Pitu Caju 350ml', 'Cachacas', 'Cachaça', 0, 7.0, false, 'un', 'Estoque: 6'),
  ('Tequiloka 1L', 'Cachacas', 'Cachaça', 0, 22.0, false, 'un', 'Estoque: 5'),
  ('Pitu Limão 965ml', 'Cachacas', 'Cachaça', 0, 15.0, false, 'un', 'Estoque: 6'),
  ('Corote Blueberry', 'Cachacas', 'Cachaça', 0, 6.0, false, 'un', 'Estoque: 3'),
  ('Duelo Maracujá', 'Cachacas', 'Cachaça', 0, 5.0, false, 'un', 'Estoque: 2'),
  ('Cachaça Do Barril 500ml', 'Cachacas', 'Cachaça', 0, 5.0, false, 'un', 'Estoque: 13'),
  ('Seleta Ouro', 'Cachacas', 'Cachaça', 0, 35.0, false, 'un', 'Estoque: 3'),
  ('Duelo Melancia', 'Cachacas', 'Cachaça', 0, 5.0, false, 'un', 'Estoque: 3'),
  ('Aperol', 'Cachacas', 'Cachaça', 0, 50.0, false, 'un', 'Estoque: 3'),
  ('Montila cristal', 'Cachacas', 'Cachaça', 0, 35.0, false, 'un', 'Estoque: 6'),
  ('Pitu 350ml', 'Cachacas', 'Cachaça', 0, 6.0, false, 'un', 'Estoque: 66'),
  ('Pitu 473ml', 'Cachacas', 'Cachaça', 0, 8.5, false, 'un', 'Estoque: 22'),
  ('Pitu mel e limão 350ml', 'Cachacas', 'Cachaça', 0, 6.5, false, 'un', 'Estoque: 58'),
  ('Caneca Stanley 710ml', 'Acessorios', 'Linha Stanley', 0, 65.0, false, 'un', 'Estoque: 0'),
  ('Stanley fonte certa', 'Acessorios', 'Linha Stanley', 0, 50.0, false, 'un', 'Estoque: 0'),
  ('Dose de Gin', 'Doses', 'Doses', 0, 0, false, 'un', 'Estoque: 0'),
  ('Dose de Vodka', 'Doses', 'Doses', 0, 0, false, 'un', 'Estoque: 0'),
  ('Dose de Whisky', 'Doses', 'Doses', 0, 0, false, 'un', 'Estoque: 0'),
  ('Shot Ballena Coco', 'Doses', 'Shot''s', 0, 12.0, false, 'un', 'Estoque: 2'),
  ('Shot Licor Bardêra Avelã', 'Doses', 'Shot''s', 0, 15.0, false, 'un', 'Estoque: 2'),
  ('Shot Licor Japira Melancia', 'Doses', 'Shot''s', 0, 3.0, false, 'un', 'Estoque: 3'),
  ('Shot Licor Don Luiz', 'Doses', 'Shot''s', 0, 10.0, false, 'un', 'Estoque: 12'),
  ('Vinho Sangue de Boi 4L', 'Vinhos', 'Vinho', 0, 85.0, false, 'un', 'Estoque: 3'),
  ('Vinho Don Nogueira seco', 'Vinhos', 'Vinho', 0, 15.0, false, 'un', 'Estoque: 4'),
  ('Vinho Santomé seco', 'Vinhos', 'Vinho', 0, 20.0, false, 'un', 'Estoque: 8'),
  ('Catuaba Açaí Selvagem', 'Vinhos', 'Vinho', 0, 17.5, false, 'un', 'Estoque: 18'),
  ('Catuaba Selvagem', 'Vinhos', 'Vinho', 0, 17.5, false, 'un', 'Estoque: 9'),
  ('Vinho Rosé Piscine 750ml', 'Vinhos', 'Vinho', 0, 80.0, false, 'un', 'Estoque: 4'),
  ('Vinho Don Nogueira Branco', 'Vinhos', 'Vinho', 0, 15.0, false, 'un', 'Estoque: 4'),
  ('Jurupinga Dinalle', 'Vinhos', 'Vinho', 0, 30.0, false, 'un', 'Estoque: 5'),
  ('Vinho Pérgola Suave 1L', 'Vinhos', 'Vinho', 0, 25.0, false, 'un', 'Estoque: 18'),
  ('Vinho Pérgola Seco 750ml', 'Vinhos', 'Vinho', 0, 25.0, false, 'un', 'Estoque: 12'),
  ('Vinho de mesa Don Nogueira suave 900ml', 'Vinhos', 'Vinho', 0, 15.0, false, 'un', 'Estoque: 4'),
  ('Cantinho do Vale 880ml', 'Vinhos', 'Vinho', 0, 5.5, false, 'un', 'Estoque: 41'),
  ('Vinho pérgola seco', 'Vinhos', 'Vinho', 0, 25.0, false, 'un', 'Estoque: 8'),
  ('Japira Menta', 'Destilados', 'Bob Pinga', 0, 20.0, false, 'un', 'Estoque: 6'),
  ('Japira Pessego', 'Destilados', 'Bob Pinga', 0, 20.0, false, 'un', 'Estoque: 5'),
  ('Japira Maça', 'Destilados', 'Bob Pinga', 0, 20.0, false, 'un', 'Estoque: 4'),
  ('Japira Cajuzinho 935 ml', 'Destilados', 'Bob Pinga', 0, 20.0, false, 'un', 'Estoque: 3'),
  ('Japira Abacaxi', 'Destilados', 'Bob Pinga', 0, 20.0, false, 'un', 'Estoque: 3'),
  ('Japira Melancia 935ml', 'Destilados', 'Bob Pinga', 0, 20.0, false, 'un', 'Estoque: 4'),
  ('Japira Limão', 'Destilados', 'Bob Pinga', 0, 20.0, false, 'un', 'Estoque: 5'),
  ('Japira Bananinha 935ml', 'Destilados', 'Bob Pinga', 0, 20.0, false, 'un', 'Estoque: 1'),
  ('Bob Pinga 975 ml', 'Destilados', 'Bob Pinga', 0, 25.0, false, 'un', 'Estoque: 5'),
  ('Cigarros', 'Tabacaria', 'Tabacaria', 0, 0, false, 'un', 'Estoque: 0'),
  ('Headshop', 'Tabacaria', 'Tabacaria', 0, 0, false, 'un', 'Estoque: 0'),
  ('Tudo para Narguilé', 'Tabacaria', 'Tabacaria', 0, 0, false, 'un', 'Estoque: 0'),
  ('Baralho Copag 139', 'Tabacaria', 'Tabacaria', 0, 30.0, false, 'un', 'Estoque: 1'),
  ('Boné Raw', 'Tabacaria', 'Tabacaria', 0, 150.0, false, 'un', 'Estoque: 1'),
  ('Narguilé Alfarid Pequeno', 'Tabacaria', 'Tabacaria', 0, 150.0, false, 'un', 'Estoque: 3'),
  ('Narguilé Alfarid Grande', 'Tabacaria', 'Tabacaria', 0, 250.0, false, 'un', 'Estoque: 1'),
  ('Monster', 'Energeticos', 'Energético & Gelo', 0, 0, false, 'un', 'Estoque: 0'),
  ('Energético Vibe & Baly', 'Energeticos', 'Energético & Gelo', 0, 0, false, 'un', 'Estoque: 0'),
  ('Mister Hemp', 'Energeticos', 'Energético & Gelo', 0, 0, false, 'un', 'Estoque: 0'),
  ('Frutas e Especiarias Gin', 'Energeticos', 'Energético & Gelo', 0, 0, false, 'un', 'Estoque: 0'),
  ('Gelos', 'Energeticos', 'Energético & Gelo', 0, 0, false, 'un', 'Estoque: 0'),
  ('Redbull', 'Energeticos', 'Energético & Gelo', 0, 0, false, 'un', 'Estoque: 0'),
  ('Espeto de Coração', 'Churrasco', 'Área do churrasco', 0, 29.0, false, 'un', 'Estoque: 0'),
  ('Espeto de Panceta Suina', 'Churrasco', 'Área do churrasco', 0, 28.0, false, 'un', 'Estoque: 0'),
  ('Kit Churrasco 1 serve até 5 pessoas', 'Churrasco', 'Área do churrasco', 0, 107.0, false, 'un', 'Estoque: 0'),
  ('Espetos de Carne 1kg (10 unidades)', 'Churrasco', 'Área do churrasco', 0, 52.0, false, 'un', 'Estoque: 0'),
  ('Kit Churrasco 4 serve até 12 pessoas', 'Churrasco', 'Área do churrasco', 0, 225.0, false, 'un', 'Estoque: 0'),
  ('Espetos Kaft com queijo 500g (5 unidades)', 'Churrasco', 'Área do churrasco', 0, 30.0, false, 'un', 'Estoque: 0'),
  ('Espetos de Linguiça 500g (5 unidades)', 'Churrasco', 'Área do churrasco', 0, 18.0, false, 'un', 'Estoque: 0'),
  ('Espetos de medalhão 500g (5 unidades)', 'Churrasco', 'Área do churrasco', 0, 35.0, false, 'un', 'Estoque: 0'),
  ('Espetos de Frango com Bacon 1kg (10 unidades)', 'Churrasco', 'Área do churrasco', 0, 43.0, false, 'un', 'Estoque: 0'),
  ('Espetos de Picanha 500g (5 unidades', 'Churrasco', 'Área do churrasco', 0, 59.0, false, 'un', 'Estoque: 0'),
  ('Espetos de Frango 500g (5 unidades)', 'Churrasco', 'Área do churrasco', 0, 23.0, false, 'un', 'Estoque: 0'),
  ('Pão de alho Santa Massa', 'Churrasco', 'Área do churrasco', 0, 15.6, false, 'un', 'Estoque: 0'),
  ('Caixa Cooler', 'Churrasco', 'Área do churrasco', 0, 19.9, false, 'un', 'Estoque: 0'),
  ('Kit Churrasco 2 serve até 7 pessoas', 'Churrasco', 'Área do churrasco', 0, 155.0, false, 'un', 'Estoque: 0'),
  ('Kit Churrasco 3 serve até 10 pessoas', 'Churrasco', 'Área do churrasco', 0, 205.0, false, 'un', 'Estoque: 0'),
  ('Smirnoff Ice Frutas Tropicas', 'Cervejas', 'Skol Beats e Ice', 0, 9.0, false, 'un', 'Estoque: 49'),
  ('Skol Beats Gt Long neck', 'Cervejas', 'Skol Beats e Ice', 0, 7.5, false, 'un', 'Estoque: 48'),
  ('Skol Beats Green mix Frutas verdes', 'Cervejas', 'Skol Beats e Ice', 0, 7.0, false, 'un', 'Estoque: 12'),
  ('Skol Beats Red mix Long neck', 'Cervejas', 'Skol Beats e Ice', 0, 7.5, false, 'un', 'Estoque: 35'),
  ('51 ice maça verde', 'Cervejas', 'Skol Beats e Ice', 0, 7.0, false, 'un', 'Estoque: 9'),
  ('51 ice melancia', 'Cervejas', 'Skol Beats e Ice', 0, 7.0, false, 'un', 'Estoque: 46'),
  ('Smirnoff Ice Framboesa', 'Cervejas', 'Skol Beats e Ice', 0, 9.0, false, 'un', 'Estoque: 21'),
  ('Skol Beats Senses Long neck', 'Cervejas', 'Skol Beats e Ice', 0, 7.5, false, 'un', 'Estoque: 55'),
  ('51 Ice Kiwi', 'Cervejas', 'Skol Beats e Ice', 0, 7.0, false, 'un', 'Estoque: 68'),
  ('51 Ice Limão', 'Cervejas', 'Skol Beats e Ice', 0, 7.0, false, 'un', 'Estoque: 19'),
  ('Smirnoff Ice', 'Cervejas', 'Skol Beats e Ice', 0, 8.5, false, 'un', 'Estoque: 7'),
  ('Beats Green Frutas Verdes', 'Cervejas', 'Skol Beats e Ice', 0, 7.5, false, 'un', 'Estoque: 37'),
  ('51 Ice Morango e Laranja', 'Cervejas', 'Skol Beats e Ice', 0, 7.0, false, 'un', 'Estoque: 118'),
  ('51 Ice Maracujá', 'Cervejas', 'Skol Beats e Ice', 0, 7.0, false, 'un', 'Estoque: 63'),
  ('Smirnoff Ice Maçã verde', 'Cervejas', 'Skol Beats e Ice', 0, 9.0, false, 'un', 'Estoque: 37'),
  ('Drink Malibu', 'Drinks', 'Drinks Prontos', 0, 30.0, false, 'un', 'Estoque: 0'),
  ('Jack Daniel´s & coca cola', 'Drinks', 'Drinks Prontos', 0, 13.0, false, 'un', 'Estoque: 3'),
  ('Jack Daniel´s mel & Limonada', 'Drinks', 'Drinks Prontos', 0, 13.0, false, 'un', 'Estoque: 7'),
  ('Xeque mate', 'Drinks', 'Drinks Prontos', 0, 9.0, false, 'un', 'Estoque: 24'),
  ('Mascate Drink Maracujá', 'Drinks', 'Drinks Prontos', 0, 10.0, false, 'un', 'Estoque: 6'),
  ('Mascate Drink Melancia e Framboesa', 'Drinks', 'Drinks Prontos', 0, 10.0, false, 'un', 'Estoque: 2'),
  ('Champanhe Aviva Gold', 'Outros', 'Variados', 0, 100.0, false, 'un', 'Estoque: 1'),
  ('Champanhe Aviva Blue', 'Outros', 'Variados', 0, 100.0, false, 'un', 'Estoque: 1'),
  ('Gemma Di Luna Moscato', 'Outros', 'Variados', 0, 20.0, false, 'un', 'Estoque: 0'),
  ('Carvão 8kg', 'Outros', 'Variados', 0, 60.0, false, 'un', 'Estoque: 2'),
  ('Carvão 2kg', 'Outros', 'Variados', 0, 17.0, false, 'un', 'Estoque: 15'),
  ('Chandon passion', 'Outros', 'Variados', 0, 95.0, false, 'un', 'Estoque: 2'),
  ('Carvão 4kg', 'Outros', 'Variados', 0, 32.0, false, 'un', 'Estoque: 16'),
  ('Vodka - Garrafa', 'Destilados', 'Whisky, Vodka, Gin e Licor', 0, 0, false, 'un', 'Estoque: 0'),
  ('Gin - Combo ou Garrafa', 'Destilados', 'Whisky, Vodka, Gin e Licor', 0, 0, false, 'un', 'Estoque: 0'),
  ('Vodka - Combo', 'Destilados', 'Whisky, Vodka, Gin e Licor', 0, 0, false, 'un', 'Estoque: 0'),
  ('Whisky - Combo', 'Destilados', 'Whisky, Vodka, Gin e Licor', 0, 0, false, 'un', 'Estoque: 0'),
  ('Licor - Combo ou Garrafa', 'Destilados', 'Whisky, Vodka, Gin e Licor', 0, 0, false, 'un', 'Estoque: 0'),
  ('Whisky - Garrafa', 'Destilados', 'Whisky, Vodka, Gin e Licor', 0, 0, false, 'un', 'Estoque: 0'),
  ('Cerveja Lata (unidade)', 'Cervejas', 'Cervejas', 0, 0, false, 'un', 'Estoque: 0'),
  ('Cerveja Pack (caixinha)', 'Cervejas', 'Cervejas', 0, 0, false, 'un', 'Estoque: 0'),
  ('Cerveja Long Neck (unidade)', 'Cervejas', 'Cervejas', 0, 0, false, 'un', 'Estoque: 0'),
  ('Don Luiz 750ml', 'Promocoes', 'Promoção da Semana', 0, 80.0, false, 'un', 'Estoque: 9'),
  ('Caipirinha de Seriguela', 'Promocoes', 'Promoção da Semana', 0, 10.0, false, 'un', 'Estoque: 0'),
  ('Gota De Cristal Ice Maçã', 'Drinks', 'Gota De Cristal Ice (Copo com Gelo)', 0, 6.5, false, 'un', 'Estoque: 9'),
  ('Gota De Cristal Blueberry', 'Drinks', 'Gota De Cristal Ice (Copo com Gelo)', 0, 6.5, false, 'un', 'Estoque: 5'),
  ('Gota de Cristal Gelo De Agua', 'Drinks', 'Gota De Cristal Ice (Copo com Gelo)', 0, 6.5, false, 'un', 'Estoque: 11'),
  ('Gota de Cristal Maracujá', 'Drinks', 'Gota De Cristal Ice (Copo com Gelo)', 0, 6.5, false, 'un', 'Estoque: 18'),
  ('Gota de Cristal Melancia', 'Drinks', 'Gota De Cristal Ice (Copo com Gelo)', 0, 6.5, false, 'un', 'Estoque: 6'),
  ('Gota de Cristal Frutas Tropicais', 'Drinks', 'Gota De Cristal Ice (Copo com Gelo)', 0, 6.5, false, 'un', 'Estoque: 14'),
  ('Gota de Cristal Morango', 'Drinks', 'Gota De Cristal Ice (Copo com Gelo)', 0, 6.5, false, 'un', 'Estoque: 24'),
  ('Gota de Cristal Ice Coco', 'Drinks', 'Gota De Cristal Ice (Copo com Gelo)', 0, 6.5, false, 'un', 'Estoque: 18'),
  ('Mansão Maromba Whisky Puro 750ml', 'Energeticos', 'SABOOR ENERGÉTICO Mansão Maromba', 0, 35.0, false, 'un', 'Estoque: 2'),
  ('Mansão Maromba Whisky', 'Energeticos', 'SABOOR ENERGÉTICO Mansão Maromba', 0, 16.0, false, 'un', 'Estoque: 6'),
  ('Mansão Maromba Double Darkness', 'Energeticos', 'SABOOR ENERGÉTICO Mansão Maromba', 0, 16.0, false, 'un', 'Estoque: 45'),
  ('Mansão Maromba Job', 'Energeticos', 'SABOOR ENERGÉTICO Mansão Maromba', 0, 16.0, false, 'un', 'Estoque: 2'),
  ('Mansão Maromba whisky  Sabor Cajuína', 'Energeticos', 'SABOOR ENERGÉTICO Mansão Maromba', 0, 16.0, false, 'un', 'Estoque: 51'),
  ('Mini Jack Fire 50 ml', 'Kits', 'Kits & Mini Bebidas', 0, 30.0, false, 'un', 'Estoque: 0'),
  ('Mini Jack Daniel’s Mel 375ml', 'Kits', 'Kits & Mini Bebidas', 0, 55.0, false, 'un', 'Estoque: 6'),
  ('Mini Cavalo Branco 500ml', 'Kits', 'Kits & Mini Bebidas', 0, 40.0, false, 'un', 'Estoque: 4'),
  ('Kit Whisky Fireball', 'Kits', 'Kits & Mini Bebidas', 0, 110.0, false, 'un', 'Estoque: 2'),
  ('Mini Absolut Lime', 'Kits', 'Kits & Mini Bebidas', 0, 15.0, false, 'un', 'Estoque: 0'),
  ('Mini Absolut Citron', 'Kits', 'Kits & Mini Bebidas', 0, 15.0, false, 'un', 'Estoque: 0'),
  ('Mini Absolut Baunilha', 'Kits', 'Kits & Mini Bebidas', 0, 15.0, false, 'un', 'Estoque: 0'),
  ('Mini absolut Raspberry', 'Kits', 'Kits & Mini Bebidas', 0, 15.0, false, 'un', 'Estoque: 0'),
  ('Mini Absolut Melancia', 'Kits', 'Kits & Mini Bebidas', 0, 15.0, false, 'un', 'Estoque: 0'),
  ('Mini Jack Daniel’s Tradicional 375ml', 'Kits', 'Kits & Mini Bebidas', 0, 55.0, false, 'un', 'Estoque: 6'),
  ('Mini Black Label 50 ml', 'Kits', 'Kits & Mini Bebidas', 0, 20.0, false, 'un', 'Estoque: 0'),
  ('Mini Chivas 12 anos 50 ml', 'Kits', 'Kits & Mini Bebidas', 0, 18.0, false, 'un', 'Estoque: 0'),
  ('Mini Kit Absolut Sabores', 'Kits', 'Kits & Mini Bebidas', 0, 75.0, false, 'un', 'Estoque: 2'),
  ('Mini Red Label', 'Kits', 'Kits & Mini Bebidas', 0, 15.0, false, 'un', 'Estoque: 0'),
  ('Mini Vodka Belvedere', 'Kits', 'Kits & Mini Bebidas', 0, 30.0, false, 'un', 'Estoque: 0'),
  ('Mini Beefeater gin 50 ml', 'Kits', 'Kits & Mini Bebidas', 0, 15.0, false, 'un', 'Estoque: 0'),
  ('Kit Jack Gentleman', 'Kits', 'Kits & Mini Bebidas', 0, 220.0, false, 'un', 'Estoque: 1'),
  ('Halls cereja', 'Salgadinhos', 'Doces e salgadinhos', 0, 2.5, false, 'un', 'Estoque: 27'),
  ('Halls preto', 'Salgadinhos', 'Doces e salgadinhos', 0, 2.5, false, 'un', 'Estoque: 2'),
  ('Doce bananinha tradição 35g', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 17'),
  ('Fini bananas', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 10'),
  ('Trident canela', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 17'),
  ('Fini Tutti-fruti 80g', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 3'),
  ('Paçoca com chocolate', 'Salgadinhos', 'Doces e salgadinhos', 0, 1.0, false, 'un', 'Estoque: 35'),
  ('Fini Tubes Morango citrico 80g', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 6'),
  ('Fini burguer', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 2'),
  ('Lobits Churrasco 200g', 'Salgadinhos', 'Doces e salgadinhos', 0, 10.0, false, 'un', 'Estoque: 2'),
  ('Lobits Requeijão 200g', 'Salgadinhos', 'Doces e salgadinhos', 0, 10.0, false, 'un', 'Estoque: 3'),
  ('Biscoito de polvilho', 'Salgadinhos', 'Doces e salgadinhos', 0, 4.0, false, 'un', 'Estoque: 14'),
  ('Cheetos Parmesão lua 95g', 'Salgadinhos', 'Doces e salgadinhos', 0, 12.0, false, 'un', 'Estoque: 2'),
  ('Fofura presunto', 'Salgadinhos', 'Doces e salgadinhos', 0, 4.0, false, 'un', 'Estoque: 4'),
  ('Pirulito', 'Salgadinhos', 'Doces e salgadinhos', 0, 0.5, false, 'un', 'Estoque: 0'),
  ('Tridente X Senses Melancia com menta 54g', 'Salgadinhos', 'Doces e salgadinhos', 0, 13.0, false, 'un', 'Estoque: 2'),
  ('Fofura queijo', 'Salgadinhos', 'Doces e salgadinhos', 0, 4.0, false, 'un', 'Estoque: 11'),
  ('Amendoim De Pimenta', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.5, false, 'un', 'Estoque: 8'),
  ('Halls uva verde', 'Salgadinhos', 'Doces e salgadinhos', 0, 2.5, false, 'un', 'Estoque: 45'),
  ('Batata point churrasco', 'Salgadinhos', 'Doces e salgadinhos', 0, 4.0, false, 'un', 'Estoque: 12'),
  ('Halls menta', 'Salgadinhos', 'Doces e salgadinhos', 0, 2.5, false, 'un', 'Estoque: 28'),
  ('Halls melancia', 'Salgadinhos', 'Doces e salgadinhos', 0, 2.5, false, 'un', 'Estoque: 12'),
  ('Amendoim Alho Panchito 20g', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.5, false, 'un', 'Estoque: 27'),
  ('Batata Point chips - Frango grelhado', 'Salgadinhos', 'Doces e salgadinhos', 0, 4.0, false, 'un', 'Estoque: 17'),
  ('Mentos Tutti frutti', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.5, false, 'un', 'Estoque: 5'),
  ('Fini Marshmallows Torção 80g', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 9'),
  ('Trident X Citrus Mix', 'Salgadinhos', 'Doces e salgadinhos', 0, 13.0, false, 'un', 'Estoque: 5'),
  ('Fofura cebola 70g', 'Salgadinhos', 'Doces e salgadinhos', 0, 4.0, false, 'un', 'Estoque: 6'),
  ('Snickers Tradicional', 'Salgadinhos', 'Doces e salgadinhos', 0, 4.5, false, 'un', 'Estoque: 6'),
  ('Pé de Moça', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 12'),
  ('Fini Tubes uva citrica 80g', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 3'),
  ('Batata Point chips - Cebola', 'Salgadinhos', 'Doces e salgadinhos', 0, 4.0, false, 'un', 'Estoque: 14'),
  ('Trident X Acid Berry', 'Salgadinhos', 'Doces e salgadinhos', 0, 13.0, false, 'un', 'Estoque: 6'),
  ('Bis Xtra Branco 45g', 'Salgadinhos', 'Doces e salgadinhos', 0, 5.0, false, 'un', 'Estoque: 2'),
  ('Paçoquita de chocolate', 'Salgadinhos', 'Doces e salgadinhos', 0, 2.0, false, 'un', 'Estoque: 5'),
  ('Doce Beijo com Chocolate', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 8'),
  ('Trident tutti-frutti', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 9'),
  ('Mini Oreo 35g', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 1'),
  ('Fruit-tella Morango 92g', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 4'),
  ('Trident Intense', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 4'),
  ('Trident morango', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 8'),
  ('Trident Melancia', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 6'),
  ('Trident Max Hortelã', 'Salgadinhos', 'Doces e salgadinhos', 0, 5.0, false, 'un', 'Estoque: 9'),
  ('Mentos Frutas Vermelhas', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.5, false, 'un', 'Estoque: 2'),
  ('Doce de abobora 65g', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 12'),
  ('Paçoquita', 'Salgadinhos', 'Doces e salgadinhos', 0, 1.5, false, 'un', 'Estoque: 7'),
  ('Fini Tubes Arco-íris', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 12'),
  ('Fini Ursinhos 80g', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 10'),
  ('Trident Herbal', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 13'),
  ('Trident cereja', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 4'),
  ('Trident X Senses Menta 54g', 'Salgadinhos', 'Doces e salgadinhos', 0, 13.0, false, 'un', 'Estoque: 5'),
  ('Fini dentaduras', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 1'),
  ('Halls morango', 'Salgadinhos', 'Doces e salgadinhos', 0, 2.5, false, 'un', 'Estoque: 14'),
  ('Amendoim Panchito 20g', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.5, false, 'un', 'Estoque: 27'),
  ('Salgadinho Ebicen Cebola 30g', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.5, false, 'un', 'Estoque: 3'),
  ('Lacta Chocolate ao Leite C/ Caramelo 104g', 'Salgadinhos', 'Doces e salgadinhos', 0, 12.0, false, 'un', 'Estoque: 8'),
  ('Lacta Branco C/ Caramelo 104g', 'Salgadinhos', 'Doces e salgadinhos', 0, 12.0, false, 'un', 'Estoque: 8'),
  ('Choco Biscuit Branco Bauducco', 'Salgadinhos', 'Doces e salgadinhos', 0, 8.0, false, 'un', 'Estoque: 1'),
  ('Trident Max Framboesa', 'Salgadinhos', 'Doces e salgadinhos', 0, 5.0, false, 'un', 'Estoque: 2'),
  ('Trident X Senses Morango Com Limão 54g', 'Salgadinhos', 'Doces e salgadinhos', 0, 13.0, false, 'un', 'Estoque: 6'),
  ('Fandangos 105g', 'Salgadinhos', 'Doces e salgadinhos', 0, 12.0, false, 'un', 'Estoque: 6'),
  ('Fini minhocas gelatina', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 2'),
  ('Doce De Leite 51g', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 13'),
  ('Fini beijos', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 6'),
  ('Trident menta verde', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 2'),
  ('Fini minhocas cítricas', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 3'),
  ('Batata point natural', 'Salgadinhos', 'Doces e salgadinhos', 0, 4.0, false, 'un', 'Estoque: 19'),
  ('Fini Salada De Frutas 14g', 'Salgadinhos', 'Doces e salgadinhos', 0, 2.0, false, 'un', 'Estoque: 10'),
  ('Fini Aros Morango 80g', 'Salgadinhos', 'Doces e salgadinhos', 0, 7.0, false, 'un', 'Estoque: 14'),
  ('Paçoca com chocolate branco', 'Salgadinhos', 'Doces e salgadinhos', 0, 1.0, false, 'un', 'Estoque: 84'),
  ('Doce de leite com chocolate 51g', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 25'),
  ('Mentos Mint', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.5, false, 'un', 'Estoque: 7'),
  ('Bombons Sortidos - unidade', 'Salgadinhos', 'Doces e salgadinhos', 0, 2.0, false, 'un', 'Estoque: 0'),
  ('Trident Max Menta e Blueberry', 'Salgadinhos', 'Doces e salgadinhos', 0, 5.0, false, 'un', 'Estoque: 9'),
  ('Kit kat preto', 'Salgadinhos', 'Doces e salgadinhos', 0, 5.0, false, 'un', 'Estoque: 70'),
  ('Pringles Marguerita', 'Salgadinhos', 'Doces e salgadinhos', 0, 13.0, false, 'un', 'Estoque: 4'),
  ('Pringles Queijo', 'Salgadinhos', 'Doces e salgadinhos', 0, 13.0, false, 'un', 'Estoque: 6'),
  ('Pringles Cebola', 'Salgadinhos', 'Doces e salgadinhos', 0, 13.0, false, 'un', 'Estoque: 7'),
  ('Trident hortelã', 'Salgadinhos', 'Doces e salgadinhos', 0, 3.0, false, 'un', 'Estoque: 24'),
  ('Trident X Senses 54g', 'Salgadinhos', 'Doces e salgadinhos', 0, 13.0, false, 'un', 'Estoque: 5'),
  ('Coca 200ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 3.0, false, 'un', 'Estoque: 13'),
  ('Coca Cola 600ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 7.0, false, 'un', 'Estoque: 22'),
  ('Fanta uva lata', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 7'),
  ('Del valle maracujá 1L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 10.5, false, 'un', 'Estoque: 1'),
  ('Refrigerante convenção guaraná', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 6.5, false, 'un', 'Estoque: 10'),
  ('Agua sem gás', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 3.0, false, 'un', 'Estoque: 390'),
  ('Del valle uva 290 ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 2'),
  ('Convenção Laranja 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 6.5, false, 'un', 'Estoque: 3'),
  ('Convenção Uva 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 6.5, false, 'un', 'Estoque: 2'),
  ('Convenção Limão 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 6.5, false, 'un', 'Estoque: 11'),
  ('Coca cola 350ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 149'),
  ('Schweppes 350ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 8'),
  ('Del Valle 1L Manga', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 10.5, false, 'un', 'Estoque: 2'),
  ('Guaraná Zero 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 11.0, false, 'un', 'Estoque: 10'),
  ('Coca cola 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 12.0, false, 'un', 'Estoque: 131'),
  ('Dolly guaraná 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 7.0, false, 'un', 'Estoque: 58'),
  ('Fanta Uva 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 10.0, false, 'un', 'Estoque: 5'),
  ('Del valle pêssego 290 ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 5'),
  ('Suco Sufresh Morango 1lt', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 10.0, false, 'un', 'Estoque: 12'),
  ('Suco Sufresh Morango 269ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 3'),
  ('Fanta laranja lata', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 11'),
  ('Fanta laranja 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 10.0, false, 'un', 'Estoque: 15'),
  ('Guaraná lata 350ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 97'),
  ('Agua c/ gás', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 3.0, false, 'un', 'Estoque: 24'),
  ('Sprite 350ml lata', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 7'),
  ('Fanta laranja 600ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 7.0, false, 'un', 'Estoque: 3'),
  ('Del Valle 1,5L Uva', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 7.0, false, 'un', 'Estoque: 1'),
  ('Agua saborizada Limão', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 4.0, false, 'un', 'Estoque: 6'),
  ('Agua Saborizada Melancia', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 4.0, false, 'un', 'Estoque: 6'),
  ('Agua Saborizada Tangerina', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 4.0, false, 'un', 'Estoque: 6'),
  ('H2OH Limão', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 14'),
  ('Del valle pêssego 1L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 10.5, false, 'un', 'Estoque: 3'),
  ('Del valle maracujá lata', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 7'),
  ('Del valle manga 290 ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 5.0, false, 'un', 'Estoque: 4'),
  ('Del valle uva 1L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 10.5, false, 'un', 'Estoque: 4'),
  ('Del Valle Limão 1,5L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 7.0, false, 'un', 'Estoque: 4'),
  ('Del Valle Limonada Tropical Lata', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 6.0, false, 'un', 'Estoque: 4'),
  ('Del Valle Manga e Morango 1l', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 12.0, false, 'un', 'Estoque: 5'),
  ('Del Valle Abacaxi e Tangerina 1l', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 12.0, false, 'un', 'Estoque: 7'),
  ('Del Valle Limonada Lata', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 6.0, false, 'un', 'Estoque: 5'),
  ('Fanta Laranja Retornável 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 9.0, false, 'un', 'Estoque: 16'),
  ('Agua saborizada Frutas vermelhas', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 4.0, false, 'un', 'Estoque: 6'),
  ('Del valle Limonada Pink Lata', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 6.0, false, 'un', 'Estoque: 4'),
  ('Coca cola retornável 2L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 9.0, false, 'un', 'Estoque: 41'),
  ('Sprite 200ml', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 3.0, false, 'un', 'Estoque: 3'),
  ('Del Valle Laranja 1,5L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 7.0, false, 'un', 'Estoque: 3'),
  ('Guaraná 2,5L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 11.5, false, 'un', 'Estoque: 20'),
  ('Agua de coco 1 litro', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 10.5, false, 'un', 'Estoque: 20'),
  ('Agua 1,5L', 'Bebidas Nao Alcoolicas', 'Sucos e Refrigerantes', 0, 4.5, false, 'un', 'Estoque: 26'),
  ('Caipirinha de Absolut', 'Drinks', 'Caipirinhas e Batidas', 0, 35.0, false, 'un', 'Estoque: 0'),
  ('Caipirinha Sem Álcool', 'Drinks', 'Caipirinhas e Batidas', 0, 15.0, false, 'un', 'Estoque: 0'),
  ('Caipirinha de Askov', 'Drinks', 'Caipirinhas e Batidas', 0, 16.0, false, 'un', 'Estoque: 0'),
  ('Batida de Absolut', 'Drinks', 'Caipirinhas e Batidas', 0, 40.0, false, 'un', 'Estoque: 0'),
  ('Batida de Smirnoff', 'Drinks', 'Caipirinhas e Batidas', 0, 30.0, false, 'un', 'Estoque: 0'),
  ('Batida de Velho Barreiro', 'Drinks', 'Caipirinhas e Batidas', 0, 25.0, false, 'un', 'Estoque: 0'),
  ('Caipirinha de Velho Barreiro', 'Drinks', 'Caipirinhas e Batidas', 0, 16.0, false, 'un', 'Estoque: 0'),
  ('Caipirinha de Jurupinga', 'Drinks', 'Caipirinhas e Batidas', 0, 20.0, false, 'un', 'Estoque: 0'),
  ('Espanhola', 'Drinks', 'Caipirinhas e Batidas', 0, 30.0, false, 'un', 'Estoque: 0'),
  ('Caipirinha de Smirnoff', 'Drinks', 'Caipirinhas e Batidas', 0, 25.0, false, 'un', 'Estoque: 0'),
  ('Batida de Askov', 'Drinks', 'Caipirinhas e Batidas', 0, 25.0, false, 'un', 'Estoque: 0'),
  ('Batida de Saque', 'Drinks', 'Caipirinhas e Batidas', 0, 25.0, false, 'un', 'Estoque: 0'),
  ('Caipirinha de Saque', 'Drinks', 'Caipirinhas e Batidas', 0, 25.0, false, 'un', 'Estoque: 0'),
  ('Batida Sem Álcool - Feita com leite', 'Drinks', 'Caipirinhas e Batidas', 0, 20.0, false, 'un', 'Estoque: 0');